controller_list:
  - name: fake_cuerpo_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
initial:  # Define initial robot poses per group
  - group: cuerpo
    pose: cero