# config/joint_trajectory_controller.yaml

# Controlador de las articulaciones del brazo
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: 
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
# Controlador que publica continuamente los estados/posiciones de las articulaciones. 
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  # Frecuencia en Hz